#!/bin/bash

# Author: Timothy Q Pham (phamtq)
# Date: January 18, 2023
# Version: 1.01
#
# This BASH script runs the ADB command to show the serial numbers of the connected devices
# and it uses that to run commands which install the 2 Android apps we use for testing.


# Grab the serial number from the output
# Command line explanation:
#	./adb devices 		Uses the ADB app to generated a list devices:
#				List of devices attached
#				XXXXXXXXXXXX     devices
#
#	sed -n '2 p'		Uses the sed command to display the 2nd line
#
#	sed -r 's/\s+//g'	Again, use sed to remove whitespaces

SERIAL=$(./adb devices | sed -n '2 p'| sed -e 's/\device//g' | sed -r 's/\s+//g')

# Use that serial number as a parameter to install the .apk's to the phone
#

# Check to see if the ADB command was able to sucessfully connect to the phone
if [[ -z "$SERIAL" ]]
then
	echo "An error occurred (did you enable USB debugging on the phone?)"
	exit 1
else
	# Install Ampere to measure battery health
	echo "Installing Ampere..."
	./adb -s $SERIAL install com.gombosdev.ampere.apk

	#Use PhoneDoctorPlus to run the rest of the tests
	echo "Installing PhoneDoctorPlus..."
	./adb -s $SERIAL install com.idea.PhoneDoctorPlus.apk
fi
